---
- name: Install IUS repository
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Install PHP-FPM
  yum: name=php71u-fpm state=present disablerepo=* enablerepo=ius
  ignore_errors: "{{ ansible_check_mode }}"

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration file
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf

  notify: restart php-fpm
