---
- name: Create the Nginx repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo 

- name: Install nginx
  yum: name=nginx state=present disablerepo=epel
  ignore_errors: "{{ ansible_check_mode }}"

  notify: start nginx
